# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxie" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "260911c4ca8d3d6579569ae639636b916c01e970e2e7cf8f5e795f379a4f04bb"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e43e28f96bd05e52d0f05de4c5cd3332c7ca1931300626aec1471211d8f5708"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2e0b8c5a9b2ce17067a6bad8273773240b2e4dd11a044153a8e3e35597a1575"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b680cab6a7d7ee336ba7620d55f060d1e808f67fb47d395d5a55e429d99c7242"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxie"
  desc "The Ethereum wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxie"]
    end
  end

  # No zap stanza required

end
