# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxib" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "2dcad727cafe8abbf59850c16d4ac9bc346a28f314e285c4724eaee0e06dee3b"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55d14b7882582221cd2681a4a4d4f3266ade70be5ba08106d6dda30942941410"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9386e6c874eb647ce16f2c7c8e3877f7ae3da0820472c527e748e61baf342ef3"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc799f83a81cc2ab11cd5b8698bc73200c7158f5b47c3b85a26aad45db1e0112"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxib"
  desc "The Bitcoin wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxib"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxib"]
    end
  end

  # No zap stanza required

end
