# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxib" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "60a6210d157faaa527a0e69b67da19c3d392fd16e3159abb6012e9de9057ff43"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad3329c3af8796ba5b3517468ecde4c9afa8383e4e103c823a2885cb89549d91"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13774b7bb3c26a1f34f4e21b16f5bbb897a624e8888e9187e54d1caf21beb07c"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fc0b840bd91a7b48a260123335797ed3aea049ded9d2f47498f34f52fbadc3c"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxib"
  desc "The Bitcoin wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxib"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxib"]
    end
  end

  # No zap stanza required

end
