# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxie" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "321ba90cca849a3a0bd807ce710d061096fc0b26a78dd489f24ccd2bc874ff2f"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b7704f2931790db86fc4b3dc15993ef1009b4b2f5dda53868089cd210bdd0f2"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab991229bf0e4fc84aff953b81d1bdb0f870eadc3a375add329134b8788407a2"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b8eb21c6b26dbc980b840c24e6804fcf6f9648f58b8c4004f2037ab964ce4a7"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxie"
  desc "The Ethereum wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxie"]
    end
  end

  # No zap stanza required

end
