# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxie" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "9f84f4aa0347adf1b9a7ac7ea4cea47db6b410ba47c0f20a0daaae809c7ce372"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0995859172076a9736434c5e539730d8349009cd82e99e787d7ba1c20e56d2f"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a48848e6501da31dc6e52d56f2f4e6246b0deca1579821cdb1dbbb12dd1eeba"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21fab6029e5ce88830e1d96324a1fb6bed54d8b793a9cc4c25dc414dbc1a2d1b"
      url "https://github.com/daxchain-io/daxie/releases/download/v#{version}/daxie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxie"
  desc "The Ethereum wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxie"]
    end
  end

  # No zap stanza required

end
