# This file was generated by GoReleaser. DO NOT EDIT.
cask "daxib" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "68e93d39b628430923f5a9ca01b844ba61bbd658d8d47fbe706bbcbeef4572ea"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a0b3abf99a62b63521766274b14943ee6ec660356cfb36205e73ba6a5311135"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f34bf69422c2e09fe6237e69cbb9c48cc5daab4ee8d777d5a1ea63f4b7d420f"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c366caf234923d9345745d04c5809e0afee1250eadb3faec3a880f514bd4b725"
      url "https://github.com/daxchain-io/daxib/releases/download/v#{version}/daxib_#{version}_linux_arm64.tar.gz"
    end
  end

  name "daxib"
  desc "The Bitcoin wallet for AI — agent-first CLI + MCP server"
  homepage "https://github.com/daxchain-io/daxib"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "daxib"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/daxib"]
    end
  end

  # No zap stanza required

end
