# This file was generated by GoReleaser. DO NOT EDIT.
cask "evm-tools" do
  version "0.5.5"

  on_macos do
    on_intel do
      sha256 "eb472f4bd7c968bf8299dd82c50b3991cfd5c20431118dc4239381885a0f749e"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0725070cccc3aaee98e785493d6adba533fefaecaf7f9a44108ae06158fa5d17"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25a22566c1e47cde60c5e8fb069f996573ba581adaea1348762f2f1b7999ff3d"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c87360c48c70706993642f013db723dd7a709a942f10204d33dcee6d5a0b6b9"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evm-tools"
  desc "Composable CLIs for observing EVM chains and streaming records as JSONL (evm-stream, evm-balance, and sinks for Kafka, webhooks, files, AWS SQS/SNS, PostgreSQL, and Redis)"
  homepage "https://github.com/daxchain-io/evm-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evm-stream"
  binary "evm-balance"
  binary "evm-sink-kafka"
  binary "evm-sink-webhook"
  binary "evm-sink-file"
  binary "evm-sink-aws-sqs"
  binary "evm-sink-aws-sns"
  binary "evm-sink-postgres"
  binary "evm-sink-redis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
