# This file was generated by GoReleaser. DO NOT EDIT.
cask "evm-tools" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "d92819e0c794f766fa465717cae1f33dd655f09a52098d8daa98f7d4d48a843e"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "08eaf02b18133d334e352f406f176e64485a6087d4cf0fadab849c10daa6e396"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e13a7f59ae68c547074735d31b3369fa4f1f5cac21218f5427307e011220142"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d87712cd3e6e880bf46e4b2be5194fa111dc3ac68a2b954d2a8ca20c7f8eb4fe"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evm-tools"
  desc "Composable CLIs for observing EVM chains and streaming records as JSONL (evm-stream, evm-balance, and sinks for Kafka, webhooks, files, AWS SQS/SNS, PostgreSQL, and Redis)"
  homepage "https://github.com/daxchain-io/evm-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evm-stream"
  binary "evm-balance"
  binary "evm-sink-kafka"
  binary "evm-sink-webhook"
  binary "evm-sink-file"
  binary "evm-sink-aws-sqs"
  binary "evm-sink-aws-sns"
  binary "evm-sink-postgres"
  binary "evm-sink-redis"
  binary "evm-sink-stdout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
