# This file was generated by GoReleaser. DO NOT EDIT.
cask "evm-tools" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "c255f687684ca2e6f42a700430f21715565bf208850805eb0cbcd3a3e808e5c8"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e5ce9eccf759a52ff8f898cfb7874b412e24b8c8ee6466a888c7ae102a601c5"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f72c8cfb7cbe9514f6f30596af40dfec76c5cbf9a6496c7b0ae91cc4c87b71d"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "677e6d42e7a9a174a6819c4d73decbc06d50448b92af2f32a213d0a548c21db7"
      url "https://github.com/daxchain-io/evm-tools/releases/download/v#{version}/evm-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evm-tools"
  desc "Composable CLIs for observing EVM chains and streaming records as JSONL (evm-stream, evm-balance, and sinks for Kafka, webhooks, files, AWS SQS/SNS, PostgreSQL, and Redis)"
  homepage "https://github.com/daxchain-io/evm-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evm-stream"
  binary "evm-balance"
  binary "evm-sink-kafka"
  binary "evm-sink-webhook"
  binary "evm-sink-file"
  binary "evm-sink-aws-sqs"
  binary "evm-sink-aws-sns"
  binary "evm-sink-postgres"
  binary "evm-sink-redis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
